Guilduser favorite memebership
Govrn-HQ/govrn-monorepo pull request #340
Opened 2022-12-09 14:27 UTC by amrro

## Linear Ticket

[PRO-687 - Add Favorite and membership status level columns to GuildUser](https://linear.app/govrn/issue/PRO-687/add-favorite-and-membership-status-level-columns-to-guilduser)

## Description
Changes to `GuildUser` Table:
- Add boolean favorite column.
- Add FK column to `GuildMembershipStatus` table, with default value for existing records corresponds to **Supporter** id

2022-12-09 14:31 UTC, amrro commented
[Don't merge from staging](https://github.com/Govrn-HQ/govrn-monorepo/pull/339#issuecomment-1344308159)

2022-12-15 15:22 UTC, alexkeating requested changes

2022-12-15 15:22 UTC, alexkeating commented on apps/protocol-api/src/prisma/schema.prisma
> +  @@unique([user_id, guild_id, membership_status_id])
The same member can have different statuses in a guild? I don't  think we want to support that use vase

2022-12-15 17:46 UTC, alexkeating commented on apps/protocol-api/src/prisma/migrations/20221209134100_add_favorite_membership_status/migration.sql
> +ON CONFLICT DO NOTHING;
Remove and include in the protocol-api/sql

2022-12-16 16:37 UTC, alexkeating approved these changes

2022-12-16 16:38 UTC, merged